import '@/styles/globals.scss'
import type { AppProps } from 'next/app'
import store from '@/store/store';
import {Provider} from 'react-redux';
import {persistStore} from 'redux-persist';
import {PersistGate} from 'redux-persist/integration/react';
import Head from 'next/head';
let persistor = persistStore(store)

export default function App({ Component, pageProps }: AppProps) {
  return (
<>
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <Component {...pageProps} />
    </PersistGate>
  </Provider>
</>
  )
}
